apiVersion: v1
kind: Service
metadata:
  name: avgcxr-rabbitmq
  namespace: avgcxr
  labels:
    app: avgcxr-rabbitmq
    component: rabbitmq
    tier: backend
    part-of: avgcxr-portal
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP
  selector:
    app: avgcxr-rabbitmq
