package in.elcot.avgcxr.platformsecurity.rbac;

public enum Permission {
  SCHEME_READ,
  SCHEME_WRITE,
  SCHEME_PUBLISH,
  APPLICATION_READ,
  APPLICATION_WRITE,
  APPLICATION_REVIEW,
  APPLICATION_APPROVE,
  USER_READ,
  USER_WRITE,
  USER_ADMIN,
  WORKFLOW_MANAGE,
  REPORT_READ,
  REPORT_EXPORT,
  NOTIFICATION_SEND,
  FILE_UPLOAD,
  FILE_DELETE,
  ANALYTICS_READ,
  HELPDESK_MANAGE,
  GRIEVANCE_MANAGE,
  ECOSYSTEM_READ,
  ECOSYSTEM_WRITE
}
