apiVersion: v1
kind: ConfigMap
metadata:
  name: avgcxr-api-config
  namespace: avgcxr
  labels:
    app: avgcxr-api
    component: api
    part-of: avgcxr-portal
data:
  application.yml: |
    spring:
      profiles:
        active: kubernetes
      datasource:
        url: jdbc:postgresql://avgcxr-pgbouncer:6432/avgcxr_portal?prepareThreshold=0
        username: avgcxr_app
      redis:
        host: avgcxr-redis
        port: 6379
      rabbitmq:
        host: avgcxr-rabbitmq
        port: 5672
        virtual-host: /avgcxr
      elasticsearch:
        uris: http://avgcxr-elasticsearch:9200
      minio:
        endpoint: http://avgcxr-minio:9000
