apiVersion: v1
kind: ConfigMap
metadata:
  name: avgcxr-cms-config
  namespace: avgcxr
  labels:
    app: avgcxr-cms
    component: cms
    part-of: avgcxr-portal
data:
  server.js: |
    module.exports = ({ env }) => ({
      host: '0.0.0.0',
      port: 1337,
      url: 'https://cms.avgcxr.elcot.tn.gov.in',
      proxy: true,
    });
