apiVersion: v1
kind: Service
metadata:
  name: avgcxr-cms
  namespace: avgcxr
  labels:
    app: avgcxr-cms
    component: cms
    tier: backend
    part-of: avgcxr-portal
spec:
  type: ClusterIP
  ports:
    - name: cms
      port: 1337
      targetPort: 1337
      protocol: TCP
  selector:
    app: avgcxr-cms
