apiVersion: v1
kind: Service
metadata:
  name: avgcxr-pgbouncer
  namespace: avgcxr
  labels:
    app: avgcxr-pgbouncer
    component: pgbouncer
    tier: backend
    part-of: avgcxr-portal
spec:
  type: ClusterIP
  ports:
    - name: pgbouncer
      port: 6432
      targetPort: 6432
      protocol: TCP
  selector:
    app: avgcxr-pgbouncer
