apiVersion: v1
kind: ConfigMap
metadata:
  name: avgcxr-postgres-config
  namespace: avgcxr
  labels:
    app: avgcxr-postgres
    component: postgres
    part-of: avgcxr-portal
data:
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 200
    shared_buffers = 1GB
    effective_cache_size = 3GB
    wal_level = replica
    max_wal_size = 2GB
    log_min_duration_statement = 500
    log_checkpoints = on
    autovacuum = on
    autovacuum_max_workers = 3
