apiVersion: v1
kind: Service
metadata:
  name: avgcxr-postgres
  namespace: avgcxr
  labels:
    app: avgcxr-postgres
    component: postgres
    tier: backend
    part-of: avgcxr-portal
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: avgcxr-postgres
