apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: "2.53.0"

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceName: Tempo
          matcherRegex: '"trace_id"\s*:\s*"([a-f0-9]+)"'
          name: TraceID
          url: '$${__value.raw}'

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      nodeGraph:
        enabled: true
      search:
        hide: false
      traceQuery:
        maxDuration: 300s
        minDuration: 1ms
        spanMetadata:
          key: trace_id
          value: trace_id
      serviceMap:
        datasourceId: Prometheus
      metricsQuery:
        datasourceId: Prometheus

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    editable: false
    database: "avgcxr-*"
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.12.0"
      logMessageField: message
      logLevelField: level
      maxConcurrentShardRequests: 5
      dataLinks:
        - datasourceUid: tempo
          field: trace_id
          url: '$${__value.raw}'