apiVersion: v1
kind: Service
metadata:
  name: avgcxr-elasticsearch
  namespace: avgcxr
  labels:
    app: avgcxr-elasticsearch
    component: elasticsearch
    tier: backend
    part-of: avgcxr-portal
spec:
  type: ClusterIP
  ports:
    - name: elasticsearch
      port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    app: avgcxr-elasticsearch
