package in.elcot.avgcxr.common.infrastructure.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.servers.Server;
import java.util.List;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * OpenAPI 3 / Swagger UI configuration for the AVGC-XR Portal API.
 *
 * <p>springdoc-openapi exposes the live API contract at:
 *
 * <ul>
 *   <li>{@code /v3/api-docs} — OpenAPI 3 document (JSON)
 *   <li>{@code /v3/api-docs.yaml} — OpenAPI 3 document (YAML)
 *   <li>{@code /swagger-ui.html} — interactive Swagger UI
 * </ul>
 *
 * <p><b>Security wiring required:</b> the Spring Security filter chain must permit
 * {@code /v3/api-docs/**}, {@code /swagger-ui/**} and {@code /swagger-ui.html}, or
 * these endpoints return {@code 401}. That permit is a follow-up requiring a
 * backend build to verify (see docs/REMEDIATION-ROADMAP.md, goals 15/34). In
 * production, Swagger UI should be disabled or restricted to internal networks
 * via {@code springdoc.swagger-ui.enabled=false} on the prod profile.
 */
@Configuration
public class OpenApiConfig {

  /**
   * Top-level API metadata served at {@code /v3/api-docs}. Per-endpoint schemas are
   * generated by springdoc from the controllers and Bean Validation annotations.
   */
  @Bean
  public OpenAPI avgcXrOpenAPI(
      @Value("${spring.application.name:avgcxr-api}") String applicationName) {
    return new OpenAPI()
        .info(
            new Info()
                .title("Tamil Nadu AVGC-XR Portal API")
                .description(
                    "REST API for the Tamil Nadu AVGC-XR Portal (ELCOT tender "
                        + "ELCOT-ST-FPP-2026-0026) — scheme and incentive applications, "
                        + "workflow approvals, ecosystem registries (Business Connect, "
                        + "Talent Connect, Freelancer Registry), documents, notifications "
                        + "and administration.")
                .version("v1")
                .contact(new Contact().name("ELCOT").email("facilitation@elcot.in"))
                .license(new License().name("Proprietary — © ELCOT")))
        .servers(List.of(new Server().url("/").description(applicationName)));
  }
}
