apiVersion: v1
kind: Service
metadata:
  name: avgcxr-minio
  namespace: avgcxr
  labels:
    app: avgcxr-minio
    component: minio
    tier: backend
    part-of: avgcxr-portal
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: console
      port: 9001
      targetPort: 9001
      protocol: TCP
  selector:
    app: avgcxr-minio
