apiVersion: v1
kind: ConfigMap
metadata:
  name: avgcxr-redis-config
  namespace: avgcxr
  labels:
    app: avgcxr-redis
    component: redis
    part-of: avgcxr-portal
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    protected-mode yes
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    timeout 300
    save 900 1
    save 300 10
    save 60 10000
