apiVersion: v1
kind: Service
metadata:
  name: avgcxr-redis
  namespace: avgcxr
  labels:
    app: avgcxr-redis
    component: redis
    tier: backend
    part-of: avgcxr-portal
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: avgcxr-redis
